select * from customers limit 100;
drop table customers;

-- Q1 What is the total revenue generated by male vs female 
SELECT 
    gender, SUM(`Purchase_Amount_(USD)`) AS revenue
FROM
    customers
GROUP BY gender;

-- Q2 Which customer used a discount but still spent more than the average purchase amount
SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer);
            
-- Q3 Whih are the top 5 products with the highest average review rating

select item_purchased, round(avg(review_rating),2) as 'Average Review Rating' 
from customer 
group by item_purchased 
order by avg(review_rating) desc 
limit 5;    

-- Q4 Compare the average purchase amount between standard and express shipping

SELECT 
    shipping_type, AVG(purchase_amount)
FROM
    customer
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

-- Q5 Do subscribed customers spends more? Compare average spend and total revenue between subscribed and non subscribers

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_Customer,
    round(avg(purchase_amount),2) AS average_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM
    customer
GROUP BY subscription_status
ORDER BY total_revenue,  average_spend desc;

-- Q6 Which 5 products have the highest percentage of purchases with discount applied

SELECT 
    item_purchased,
    (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0) / COUNT(*) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7 Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and shows the count of each segment.

with customer_type as (
select customer_id, previous_purchases, 
case 
when previous_purchases = 1 then 'New' 
when previous_purchases between 2 and 10 then 'Returning' 
else 'Loyal' 
end as customer_segment 
from customer
) 
 select customer_segment , count(*) as 'Number of customers'
 from customer_type
 group by customer_segment;
 
 -- Q8 What are the top 3 most purchased product within each category
 
 with item_counts as (
 select category, item_purchased, count(customer_id) as total_orders, 
 row_number() over(partition by category order by count(customer_id) desc) as item_rank
 from customer
 group by category, item_purchased
 )
 select item_rank, category, item_purchased, total_orders
 from item_counts
 where item_rank <=3;
 
 -- Q9 Are customers who are repeat buyers (more then 5 previous purchases) also likely to subscribe?
 
 select subscription_status,
 count(customer_id) as repeat_buyers
 from customer
 where previous_purchases >5
 group by subscription_status;
 
 -- Q10 What is the revenue contributed of each age group
 
 select age_group, sum(purchase_amount) as revenue from customer
 group by age_group
 order by revenue desc;
 

